
-- Project - Hello Holiday
-- This document only add test data to tables!


-- test data for table "city"
INSERT into city (name)
VALUES
('Miami'),
('Innsbruck'),
('Cape Town'),
('New York'),
('Honolul')
/*,
('Nice'),
('London'),
('Queenstown'),
('Dubai'),
('Manaus'),
('Male'),
('Tokyo'),
('Aspen'),
('Cancun'),
('Sydney')*/
;

-- test data for table "country"
INSERT into country (name)
VALUES
('USA'),
('Austria'),
('South Africa')
/*,
('France'),
('UK'),
('New Zealand'),
('United Arab Emirates'),
('Brazil'),
('Maldives'),
('Japan'),
('Cancun'),
('Australia')*/
;

-- test data for table "hotel"
INSERT INTO hotel (name, address, city_id, country_id, description, pool, entertainment, restaurant, kidsclub, beach_proximity, city_proximity)
VALUES
('Ocean Breeze Resort', '123 Ocean Drive', 1, 1, 'Luxury beachfront resort with ocean views.', true, true, true, true, 0, 10),
('Alpine Peaks Hotel', '45 Mountain Road', 2, 2, 'Scenic mountain retreat with cozy cabins.', false, false, true, false, 100, 5),
('Sunrise Haven', '7 East Sunrise Blvd', 3, 3, 'Modern rooms with panoramic sunrise views.', true, true, true, true, 2, 20),
('The Urban Escape', '33 Downtown Avenue', 4, 1, 'Trendy hotel in the heart of the city.', true, true, true, false, 50, 0),
('Palm Grove Inn', '22 Beachside Lane', 5, 1, 'Family-friendly hotel with tropical charm.', true, true, true, true, 1, 15)
/*,
('Seaside Serenity', '89 Coastal Road', 6, 4, 'Quiet hotel near pristine beaches.', false, false, true, false, 1, 25),
('The Grand Metropolitan', '1 Luxury Square', 7, 5, 'Luxurious city hotel with premium amenities.', true, true, true, false, 60, 1),
('Lakeside Lodge', '10 Serenity Way', 8, 6, 'Charming lodge by the serene lake.', false, true, true, true, 80, 10),
('Desert Mirage Hotel', '15 Desert Sands Blvd', 9, 7, 'Boutique hotel with unique desert views.', true, true, true, false, 200, 30),
('Rainforest Retreat', '5 Green Jungle St', 10, 8, 'Eco-friendly hotel in lush rainforest.', true, false, false, true, 3, 40),
('Blue Lagoon Resort', '12 Paradise Drive', 11, 9, 'Exclusive resort with private beach.', true, true, true, true, 1, 5),
('Cityscape Suites', '50 Skyline St', 12, 10, 'Elegant hotel with stunning skyline views.', false, true, true, false, 70, 2),
('Snowfall Chalet', '30 Snowy Hill Rd', 13, 1, 'Rustic retreat in snowy mountains.', false, false, true, true, 150, 8),
('Golden Sands Resort', '78 Golden Beach Rd', 14, 11, 'All-inclusive resort on golden sands.', true, true, true, true, 0, 12),
('Harbor View Inn', '2 Marina Lane', 15, 11, 'Cozy inn with picturesque harbor views.', false, true, true, false, 0, 18)*/
;

-- test data for table "room"
INSERT INTO room (hotel_id, price, description, balcony, size)
VALUES
(1, 120, 'Cozy single room with an ocean view.', true, 'Single'),
(1, 150, 'Double room with modern decor and sea breeze.', true, 'Double'),
(1, 180, 'Spacious triple room with a private balcony.', true, 'Triple'),
(1, 200, 'Luxurious quad suite with direct beach access.', true, 'Quad'),
(1, 100, 'Comfortable single room with a garden view.', false, 'Single'),
(1, 140, 'Stylish double room overlooking the pool.', true, 'Double'),
(1, 175, 'Triple room with family-friendly amenities.', false, 'Triple'),
(1, 210, 'Exclusive quad room with premium furnishings.', true, 'Quad'),
(1, 130, 'Single room with minimalist design.', false, 'Single'),
(1, 160, 'Double room with scenic ocean views.', true, 'Double'),
(2, 90, 'Charming single room with mountain views.', false, 'Single'),
(2, 110, 'Cozy double room with rustic decor.', false, 'Double'),
(2, 150, 'Triple room with panoramic alpine views.', true, 'Triple'),
(2, 180, 'Quad room with spacious seating area.', false, 'Quad'),
(2, 85, 'Basic single room ideal for solo travelers.', false, 'Single'),
(2, 130, 'Comfortable double room with balcony access.', true, 'Double'),
(2, 160, 'Family triple room with extra beds.', true, 'Triple'),
(2, 200, 'Luxury quad room with stunning mountain views.', true, 'Quad'),
(2, 95, 'Small single room with compact design.', false, 'Single'),
(2, 125, 'Double room with a cozy atmosphere.', false, 'Double'),
(3, 110, 'Modern single room with stylish decor.', false, 'Single'),
(3, 140, 'Double room with excellent city views.', true, 'Double'),
(3, 170, 'Triple room with extra living space.', true, 'Triple'),
(3, 210, 'Spacious quad room with premium furnishings.', true, 'Quad'),
(3, 100, 'Cozy single room ideal for business travelers.', false, 'Single'),
(3, 150, 'Double room with a private balcony.', true, 'Double'),
(3, 180, 'Family triple room with modern amenities.', true, 'Triple'),
(3, 220, 'Luxurious quad room with skyline views.', true, 'Quad'),
(3, 120, 'Simple single room with efficient design.', false, 'Single'),
(3, 160, 'Comfortable double room near public transport.', false, 'Double'),
(4, 135, 'Single room with chic decor in the city center.', false, 'Single'),
(4, 175, 'Double room with large windows and urban views.', true, 'Double'),
(4, 200, 'Triple room with modern design and spacious layout.', false, 'Triple'),
(4, 250, 'Quad room with luxury amenities and a balcony.', true, 'Quad'),
(4, 120, 'Single room near shopping districts.', false, 'Single'),
(4, 150, 'Double room with comfortable bedding.', true, 'Double'),
(4, 190, 'Family-friendly triple room with city access.', false, 'Triple'),
(4, 230, 'Quad room with premium furniture and views.', true, 'Quad'),
(4, 140, 'Compact single room for short stays.', false, 'Single'),
(4, 180, 'Elegant double room with great amenities.', true, 'Double'),
(5, 90, 'Single room with tropical garden views.', false, 'Single'),
(5, 120, 'Double room with private balcony and pool access.', true, 'Double'),
(5, 150, 'Triple room with kid-friendly features.', false, 'Triple'),
(5, 200, 'Quad suite with spacious living area.', true, 'Quad'),
(5, 95, 'Basic single room with comfortable bedding.', false, 'Single'),
(5, 130, 'Double room with modern decor and amenities.', false, 'Double'),
(5, 170, 'Triple room with extra beds for families.', true, 'Triple'),
(5, 210, 'Luxury quad room with beautiful views.', true, 'Quad'),
(5, 105, 'Single room ideal for solo travelers.', false, 'Single'),
(5, 140, 'Stylish double room with private balcony.', true, 'Double')
/*,
(6, 100, 'Simple single room close to the beach.', false, 'Single'),
(6, 130, 'Double room with a tropical view.', true, 'Double'),
(6, 170, 'Triple room with modern decor.', true, 'Triple'),
(6, 200, 'Quad room with luxurious furnishings.', true, 'Quad'),
(6, 90, 'Minimalist single room for travelers.', false, 'Single'),
(6, 140, 'Double room with nearby pool access.', true, 'Double'),
(6, 160, 'Triple room with family accommodations.', true, 'Triple'),
(6, 210, 'Quad suite with premium facilities.', true, 'Quad'),
(6, 120, 'Comfortable single room for short stays.', false, 'Single'),
(6, 150, 'Stylish double room with excellent amenities.', true, 'Double'),
(7, 300, 'Luxury single room with panoramic skyline views.', true, 'Single'),
(7, 350, 'Elegant double room with premium furnishings.', true, 'Double'),
(7, 400, 'Spacious triple room with a private lounge.', true, 'Triple'),
(7, 450, 'Exclusive quad suite with private balcony.', true, 'Quad'),
(7, 280, 'Comfortable single room near city center.', false, 'Single'),
(7, 320, 'Double room with urban and garden views.', true, 'Double'),
(7, 380, 'Triple room with deluxe bedding.', false, 'Triple'),
(7, 420, 'Luxurious quad room with high-end amenities.', true, 'Quad'),
(7, 310, 'Modern single room for business travelers.', false, 'Single'),
(7, 360, 'Double room with a cozy seating area.', true, 'Double'),
(8, 95, 'Rustic single room with lake views.', false, 'Single'),
(8, 125, 'Double room with private access to the lake.', true, 'Double'),
(8, 150, 'Family triple room with wooden interiors.', true, 'Triple'),
(8, 200, 'Luxury quad suite with scenic views.', true, 'Quad'),
(8, 90, 'Compact single room for solo travelers.', false, 'Single'),
(8, 120, 'Double room with vintage decor.', false, 'Double'),
(8, 170, 'Spacious triple room with modern amenities.', true, 'Triple'),
(8, 210, 'Quad room with private garden access.', true, 'Quad'),
(8, 100, 'Single room with cozy furnishings.', false, 'Single'),
(8, 140, 'Double room with balcony and lake view.', true, 'Double'),
(9, 80, 'Economical single room near the city.', false, 'Single'),
(9, 110, 'Double room with classic decor.', false, 'Double'),
(9, 140, 'Triple room with comfortable seating.', true, 'Triple'),
(9, 180, 'Quad room with stunning views.', true, 'Quad'),
(9, 85, 'Single room for budget-conscious travelers.', false, 'Single'),
(9, 120, 'Double room with basic amenities.', false, 'Double'),
(9, 160, 'Triple room with family-friendly features.', true, 'Triple'),
(9, 200, 'Luxurious quad room with modern interiors.', true, 'Quad'),
(9, 95, 'Single room with a simple layout.', false, 'Single'),
(9, 130, 'Double room with pool access.', true, 'Double'),
(10, 110, 'Comfortable single room with city views.', false, 'Single'),
(10, 140, 'Double room with direct city access.', true, 'Double'),
(10, 170, 'Triple room with additional space for families.', true, 'Triple'),
(10, 220, 'Premium quad suite with luxury furnishings.', true, 'Quad'),
(10, 100, 'Single room for short-term stays.', false, 'Single'),
(10, 130, 'Double room with garden views.', false, 'Double'),
(10, 180, 'Triple room with spacious layout.', true, 'Triple'),
(10, 240, 'Quad room with exclusive access to facilities.', true, 'Quad'),
(10, 120, 'Single room with modern design.', false, 'Single'),
(10, 150, 'Double room with contemporary decor.', true, 'Double'),
(11, 130, 'Single room with forest views.', false, 'Single'),
(11, 160, 'Double room with private balcony.', true, 'Double'),
(11, 190, 'Triple room with rustic interiors.', true, 'Triple'),
(11, 240, 'Quad suite with luxury amenities.', true, 'Quad'),
(11, 120, 'Basic single room with compact design.', false, 'Single'),
(11, 150, 'Double room with access to hiking trails.', false, 'Double'),
(11, 200, 'Triple room ideal for families.', true, 'Triple'),
(11, 270, 'Luxurious quad room with spacious seating.', true, 'Quad'),
(11, 140, 'Single room with nature-inspired decor.', false, 'Single'),
(11, 180, 'Elegant double room with modern touches.', true, 'Double'),
(12, 100, 'Single room with sea breeze and ocean views.', false, 'Single'),
(12, 140, 'Double room with a private patio.', true, 'Double'),
(12, 170, 'Triple room with family-friendly amenities.', true, 'Triple'),
(12, 220, 'Quad suite with panoramic ocean views.', true, 'Quad'),
(12, 90, 'Single room with compact space.', false, 'Single'),
(12, 120, 'Double room with sleek modern furniture.', false, 'Double'),
(12, 180, 'Triple room with extra seating and bedding.', true, 'Triple'),
(12, 250, 'Quad room with luxurious accommodations.', true, 'Quad'),
(12, 110, 'Single room ideal for short stays.', false, 'Single'),
(12, 150, 'Double room with a cozy atmosphere.', true, 'Double'),
(13, 85, 'Simple single room in a rural setting.', false, 'Single'),
(13, 115, 'Double room with warm decor.', false, 'Double'),
(13, 145, 'Triple room with scenic views.', true, 'Triple'),
(13, 195, 'Quad room with rustic charm.', true, 'Quad'),
(13, 80, 'Single room with budget-friendly pricing.', false, 'Single'),
(13, 125, 'Double room with balcony access.', true, 'Double'),
(13, 160, 'Family triple room with modern features.', true, 'Triple'),
(13, 220, 'Luxury quad room with forest views.', true, 'Quad'),
(13, 95, 'Small single room with basic amenities.', false, 'Single'),
(13, 140, 'Double room with comfortable furnishings.', true, 'Double'),
(14, 90, 'Single room near tourist attractions.', false, 'Single'),
(14, 120, 'Double room with a modern touch.', false, 'Double'),
(14, 150, 'Triple room with family-friendly furnishings.', true, 'Triple'),
(14, 210, 'Quad room with upscale decor.', true, 'Quad'),
(14, 100, 'Single room for business travelers.', false, 'Single'),
(14, 130, 'Double room with nearby dining options.', true, 'Double'),
(14, 170, 'Triple room with extra bedding.', true, 'Triple'),
(14, 230, 'Quad suite with luxury accommodations.', true, 'Quad'),
(14, 110, 'Single room with cozy layout.', false, 'Single'),
(14, 140, 'Elegant double room for couples.', true, 'Double'),
(15, 120, 'Single room with stunning mountain views.', false, 'Single'),
(15, 160, 'Double room with balcony access.', true, 'Double'),
(15, 190, 'Triple room with extra comfort.', true, 'Triple'),
(15, 250, 'Luxurious quad room with elegant decor.', true, 'Quad'),
(15, 110, 'Compact single room for solo travelers.', false, 'Single'),
(15, 150, 'Double room with convenient location.', false, 'Double'),
(15, 200, 'Triple room with spacious interiors.', true, 'Triple'),
(15, 270, 'Premium quad suite with deluxe furnishings.', true, 'Quad'),
(15, 130, 'Single room with minimalistic design.', false, 'Single'),
(15, 180, 'Double room with nearby hiking trails.', true, 'Double')*/
;

-- test data for table "customer"
INSERT INTO customer (firstname, lastname, email, phone, birth)
VALUES
('John', 'Doe', 'john.doe@example.com', '+1234567890', '1990-05-14'),
('Jane', 'Smith', 'jane.smith@example.com', '+1987654321', '1985-09-23'),
('Emily', 'Brown', 'emily.brown@example.com', '+447711223344', '1992-03-10'),
('Michael', 'Johnson', 'michael.johnson@example.com', '+14151234567', '1980-07-04'),
('Sophia', 'Davis', 'sophia.davis@example.com', '+61234567890', '1995-11-29'),
('James', 'Wilson', 'james.wilson@example.com', '+3344556677', '1988-02-14'),
('Olivia', 'Taylor', 'olivia.taylor@example.com', '+5511998765432', '1993-06-18'),
('Liam', 'Anderson', 'liam.anderson@example.com', '+34911223344', '1997-08-01'),
('Isabella', 'Thomas', 'isabella.thomas@example.com', '+819012345678', '2000-01-21'),
('Noah', 'Jackson', 'noah.jackson@example.com', '+49891234567', '1982-12-12'),
('Emma', 'Martinez', 'emma.martinez@example.com', '+521234567890', '1998-05-09'),
('Lucas', 'Hernandez', 'lucas.hernandez@example.com', '+8613801234567', '1991-09-30'),
('Mia', 'Lopez', 'mia.lopez@example.com', '+393391234567', '1987-04-17'),
('William', 'Lee', 'william.lee@example.com', '+6512345678', '1996-10-02'),
('Charlotte', 'Clark', 'charlotte.clark@example.com', '+27123456789', '1994-07-22');

INSERT into rating (hotel_id, customer_id, rating)
VALUES
(1, 1, '*****'),
(2, 2, '*****'),
(1, 3, '****'),
(4, 4, '***'),
(5, 5, '****');
